### ISSUE TITLE
use_rights for study work

### ISSUE THREAD

**Issue by zp2546265641** [Jovian-Dsouza/sahayak_bot#3]
hello,can i  use your urdf and worlds files to complete some simulation works for my master degree's study work?if i can, is there something need i to do?thanks for your answers.

**Comment by Jovian-Dsouza** [comment]
Yes, you can use it.

**Comment by Jovian-Dsouza** [comment]
You can use it. No issues. Just a Star on this repo 😅

**Comment by zp2546265641** [comment]
> You can use it. No issues. Just a Star on this repo 😅

no problem, thanks
